### ISSUE TITLE
chrN vs N chromosome names

### ISSUE THREAD

**Issue by mike2vandy** [pauline-ng/SIFT4G_Annotator#9]
Hello,

I built a sift database from fastas and gtfs all with chrN (chr1, chr2, chr3) chromosome names, my vcf has chrN chromosome names. I'm running the java annotator on the sift database and vcf and I'm getting this output: 

The following chromosomes (or scaffolds/contigs) are not found in the SIFT 4G database and will not be annotated:
22, 23, 24, 25, 26, 27, 28, 29, M, X, 30, 31, 10, 32, 11, 33, 12, 34, 13, 35, 14, 36, 15, 37, 16, 38, 17, 18, 19, 1, 2, 3, 4, 5, 6, 7, 8, 9, 20, 21
Please contact us if you have any questions.
sift_test/canfam4/1.regions does not exist
sift_test/canfam4/2.regions does not exist
...

and the output is filled with NONCODING and NAs. 

Why is this looking for 1,2,3 etc when I built everything with chr1, chr2, chr3, etc. Am I doing something wrong? I'm not that good with java, but is there a way to change this behavior?

**Comment by pauline-ng** [comment]
Hi Mike,  

I'm not good in Java either.  It's because the employee who did code it had to reconcile human build 38 start with "chr" and human build 37 did not, some users were inconsistently using chr in the genome but not in the VCF. Given these inconsistencies, this was the way she chose to reconcile it -- removing "chr" if observed.

**Comment by pauline-ng** [comment]
What are the files in sift_test/canfam4 , can you list the first few files and are they non-empty?

Here's a tip from another user who had problems with the 'chr' naming convention:

I believe the issue is finally resolved! I mentioned earlier that I had copied "chr19.regions" to "19.regions" and continued to receive the error. However, today I also tried the same thing with chr19.gz -> 19.gz and chr19_SIFTDB_stats.txt -> 19_SIFTDB_stats.txt and now the annotation seems to be working properly. The *SIFT_predictions.vcf now has annotations and they appear to line up with genes I know should be in those locations with the reference genome I'm using.

**Comment by mike2vandy** [comment]
Yes, that's what I ended up doing, remove the chr from the database file names. 

Thank you :)

**Comment by jarobin** [comment]
I also encountered this issue. The fix of renaming the database files is simple enough, but I definitely recommend adding a note about this issue to the instructions for SIFT4G_Create_Genomic_DB, and probably the SIFT4G Annotator as well. I'm sure it trips up many users.

**Comment by pauline-ng** [comment]
Thanks @jarobin for the suggestion. I've updated the README in both repositories.
